### ISSUE TITLE
New Override: enable /disable

### ISSUE THREAD

**Issue by sparky-Ol** [niklaswall/node-red-contrib-light-scheduler#29]
Hi Niklas,
is it possible to add new overrides enable/disable, which prevents the node from sending payload at all. 
My purpose is to have several scheduler, e.g one for schoolholidays and normal weeks. I want to decide which scheduler is aktive by override, depending on having holidays or not.

**Comment by niklaswall** [comment]
Yes, absolutely.. this is something that I have had a need for myself and should be very easy to implement.

Will look into it!

/Niklas

**Comment by niklaswall** [comment]
So, it turns out i have already implemented this but it's poorly documented... so bad that I had forgot about it myself :-)

Just send the override payload "stop" to the node and it will postpone output until it's turned back on with "auto" or any other override keyword.

I hope this solves your problem!

/Niklas

**Comment by sparky-Ol** [comment]
Hi Niklas,
it works, when i send override Paylaod the status chaged:
[image: grafik.png]
But after a while it changes back to on/off status?
[image: grafik.png]
Can you check this please?

Sparky

Bu

Am Mo., 29. Apr. 2019 um 12:51 Uhr schrieb Niklas Wall <
notifications@github.com>:

**Comment by niklaswall** [comment]
Your screenshots does not work. Can you please describe the problem more in detail?
