### ISSUE TITLE
No outout on start-up/deploy

### ISSUE THREAD

**Issue by tsprivate** [niklaswall/node-red-contrib-light-scheduler#30]
Hi,

I just have started to use your amazing node and like it so far. However, it does not generate an output on startup when configured.

My configured node does output based on schedule and sun-pos just not at start-up.

thanks for any advise and your great work

**Comment by niklaswall** [comment]
Are you using the 0.0.13 version released today?

#28 is kind of the same problem which i think is fixed in today's release.

The problem was related ti the output setting "when state changes" that erroneously blocked output. Changing it to "when state changes + startup" is a workaround for the problem.

Best regards,
Niklas

**Comment by tsprivate** [comment]
I must have missed the latest update ... just installed latest version and it works fine !!

Great work

**Comment by niklaswall** [comment]
Perfect, that sounds great!

/Niklas
