### ISSUE TITLE
Schedules next to each other

### ISSUE THREAD

**Issue by amblyo** [niklaswall/node-red-contrib-light-scheduler#44]
If i draw a schedule with on ending 07:00 and another one starting 07:00.

Will the first send OFF and the second ON or will it jump over to the next schedule with no state change?

**Comment by niklaswall** [comment]
No it should not send an OFF in this case... unless you have randomness enabled where it most likely will happen.

**Comment by amblyo** [comment]
Ok, thats a shame as i wanted to have it to send a payload at specific times to change brightnes.

**Comment by niklaswall** [comment]
Sorry for that!

**Comment by spudje** [comment]
I still have a similar issue. I have a schedule running from 9:00 to 1:00 the next day (without random, sun or anything). Two issues:
- I need to create 2 schedules: 1 from 9:00 till 24:00 and 1 from 24:00 - 1:00
- It triggers a turn Off at 24:00, but the second schedule is not triggered on 24:00, I assume since it's overlapping.

I would like to see an uninterrupted schedule running from one day to another.
