### ISSUE TITLE
schedule

### ISSUE THREAD

**Issue by vlak6613** [niklaswall/node-red-contrib-light-scheduler#60]
Dear niklaswall, i am trying to make a schematic in the node you made. I must honestly say that I get no further than a point and a colored box. 
I'm sure I'll do something wrong but just don't know what.

![Knipsel](https://user-images.githubusercontent.com/62911523/89176497-f2dc9680-d589-11ea-92a8-b40e4d0a51ec.JPG)

**Comment by elrogalo** [comment]
Hi there.

I am having the same issue with LS node.

I noticed today, that it is impossible to add new or modify existing scheules in Light Scheduler (LS) nodes in my flows. There seem to be display / edit error of the graphs inside the scheduler table.

All of my LS nodes contain a schedule for whole week, which should be displayed as bars. Instead of them I can only see the bar for Monday, and a dot in place of the Tuesdays bar.

![grafik](https://user-images.githubusercontent.com/69166053/89216059-11628200-d5ca-11ea-96df-38ac8a7969d2.png)

When I click on the Monday bar it "jumps" over to the Tuesdays schedule, the dot also moves also one place. That goes all the way to the end of the schedule table.

![grafik](https://user-images.githubusercontent.com/69166053/89216353-8766e900-d5ca-11ea-8e77-00f8a236b61f.png)

![grafik](https://user-images.githubusercontent.com/69166053/89216386-96e63200-d5ca-11ea-8c09-9ded18f34c3d.png)

That goes for all existing nodes.
Drawing new schedule bars deos not work as well, well it seems to work, but the coloured bar is drawn in opaque color and dissapears after releasing mouse button.
Clicking and drawing in place where a bar is supposedly present (although not visible) is causing the cursor to change to crossed circle (couldn't register than on screen capture).

Despite the display and editing problems all scheduler nodes that I have in flows are still working properly and react to override commands.
I am using Home Assistant 0.113.3 on HassOS 4.11 with Supervisor version 229 on Raspberry Pi 4B.

**Comment by elrogalo** [comment]
So, I will answer my own post, maybe it will help someone with same issue - updating the node to version 0.0.16 (from 0.0.15) solved the problem. I shoud have checked for the updates in the first place.
This issue can be closed, I guess.

Cheers
Marcin

**Comment by niklaswall** [comment]
Sorry for not answering this in time, but you are right. This was an issue with newer node-red versions and version 0.0.15 of the scheduler.

//Niklas
