### ISSUE TITLE
Node will not turn on when Sun down

### ISSUE THREAD

**Issue by SlickMick66** [niklaswall/node-red-contrib-light-scheduler#61]
Node will not turn on when it is suppose to.  My Co-ordinates seem to have the sun angle correct, got set to only when dark.
Been changing the threshold and re-deploying with no change.

![2020-08-08_18h31_49](https://user-images.githubusercontent.com/55223986/89706523-a4723200-d9a5-11ea-81dc-e0b8cb1e22ea.png)

**Comment by niklaswall** [comment]
Hi,

Have you added a schedule as well for that time?

Both the schedule and the sun pos must match for it to turn on.

//Niklas

**Comment by SlickMick66** [comment]
Ok, no. So what is the point of the sun pos when you have to create a schedule to match?

**Comment by niklaswall** [comment]
The point is that both the schedule and the sun position must match.

For example, you might want to control your outdoor lights so that they are turned on during the dark part of the day. But to save energy you don't actually need them on in the middle of the night when you are sleeping. To solve this you add a schedule when you want the lights to be able to turn on, but only if the sun has set (or is about to set).

If you live close to the equator the sunset / sunrise might only differ 30-40 minutes in time over the course of a year, but further away the difference is much greater. Where I live in the northern parts of Sweden we have midnight sun in the summer and pitch black days (almost) during the darkest parts of winter. Since the sunset / sunrise changes so much over the year, it's not feasible to control the lights based on any other method than combining both a schedule and the sun's position.

//Niklas
