### ISSUE TITLE
Dusk / Dawn overrides

### ISSUE THREAD

**Issue by tjareson** [niklaswall/node-red-contrib-light-scheduler#63]
Hello,

I'm not sure - maybe it is a misunderstanding in function / flow of the timer vs. Dusk / Down overrides.
I have a fixed time window, let's say from 20:30 to 23:00 every day to switch on and off.
Now I set the Dusk/Dawn to "Only when dark". 
1. In case it is not dark at 20:30 yet, will it not switch on at all or only switch on later, as soon as it gets dark, assumed that this point in time is still within the scheduled times?
2. And the other way around, it is earlier dark than the schedule, let's say 19:30. Will it then switch on even that the dark point of time is outside the schedule?
Beside that, thanks for the implementation - it is a very useful function in my home automation setup. :-)

Cheers
Tjareson

**Comment by niklaswall** [comment]
Hi,

both the schedule and the "is it dark?" must be true for it to turn on.

1. It will turn on if it is dark before 20:30 or if it becomes dark between 20:30 and 22:59. It will then turn off at 23:00
2. In this case it will turn on at 20:30 according to the schedule since it will be dark. And turn off at 23:00.

You can basically say that you in the schedule allows it to turn on, but it will only turn on if it's dark as well (if that option is enabled).

//Niklas
