### ISSUE TITLE
Sunrise to early!

### ISSUE THREAD

**Issue by stheinen** [niklaswall/node-red-contrib-light-scheduler#69]
The sunrise is triggered today at 7:23am and not at 8:23am CET. 
The timezone on my raspberry time is Europe/Berlin and the clock is set to the corret local time.

The hard schedule in the light scheduler is ok. Only the calculcation of dawn and sunrise seems to use a wrong time setting. 

I am using red node within iobroker. 
Does anybody else have this problem as well?

**Comment by mrjmg** [comment]
I do, so I stopped using LS. 
I was using Bigtimer next to it to check sunrise/sunset, bt was always spot on. LS sometimes, and some times an hour early (but not always).

**Comment by niklaswall** [comment]
The one hour problems smells like a Daylight Savings Time related problem. 

I would suggest that you check the "Show sun elevation in status" checkbox and compare the value shown with the threshold you have set.
<img width="352" alt="bild" src="https://user-images.githubusercontent.com/14335133/109997011-0e6e7200-7d10-11eb-810d-85f450a084c4.png">

The sun elevation will then show under the node like this:
<img width="149" alt="bild" src="https://user-images.githubusercontent.com/14335133/109997096-28a85000-7d10-11eb-8490-d6b735cd3a49.png">

Besides this, double check the clock, time zone and DST settings on your machine.

Let me know how it turns out!

//Niklas

**Comment by niklaswall** [comment]
Unable to reproduce this issue, glad to reopen if more details arise!
